// People
export const GET_PEOPLE = 'GET_PEOPLE';
export const GET_PEOPLE_SUCCESS = 'GET_PEOPLE_SUCCESS';
export const GET_PEOPLE_FAILURE = 'GET_PEOPLE_FAILURE';

// Species
export const GET_SPECIES = 'GET_SPECIES';
export const GET_SPECIES_SUCCESS = 'GET_SPECIES_SUCCESS';
export const GET_SPECIES_FAILURE = 'GET_SPECIES_FAILURE';
